// Code generated by MockGen. DO NOT EDIT.
// Source: uuid_generator_interface.go

// Package mock_uuid_generator is a generated GoMock package.
package mock_uuid_generator

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUIDGeneratorInterface is a mock of UUIDGeneratorInterface interface.
type MockUUIDGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDGeneratorInterfaceMockRecorder
}

// MockUUIDGeneratorInterfaceMockRecorder is the mock recorder for MockUUIDGeneratorInterface.
type MockUUIDGeneratorInterfaceMockRecorder struct {
	mock *MockUUIDGeneratorInterface
}

// NewMockUUIDGeneratorInterface creates a new mock instance.
func NewMockUUIDGeneratorInterface(ctrl *gomock.Controller) *MockUUIDGeneratorInterface {
	mock := &MockUUIDGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockUUIDGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDGeneratorInterface) EXPECT() *MockUUIDGeneratorInterfaceMockRecorder {
	return m.recorder
}

// NewString mocks base method.
func (m *MockUUIDGeneratorInterface) NewString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewString")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewString indicates an expected call of NewString.
func (mr *MockUUIDGeneratorInterfaceMockRecorder) NewString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewString", reflect.TypeOf((*MockUUIDGeneratorInterface)(nil).NewString))
}
