// Code generated by MockGen. DO NOT EDIT.
// Source: token_service_interface.go

// Package mock_token_service is a generated GoMock package.
package mock_token_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	auth "github.com/anoriar/gophkeeper/internal/server/user/dto/auth"
)

// MockTokenSerivceInterface is a mock of TokenSerivceInterface interface.
type MockTokenSerivceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSerivceInterfaceMockRecorder
}

// MockTokenSerivceInterfaceMockRecorder is the mock recorder for MockTokenSerivceInterface.
type MockTokenSerivceInterfaceMockRecorder struct {
	mock *MockTokenSerivceInterface
}

// NewMockTokenSerivceInterface creates a new mock instance.
func NewMockTokenSerivceInterface(ctrl *gomock.Controller) *MockTokenSerivceInterface {
	mock := &MockTokenSerivceInterface{ctrl: ctrl}
	mock.recorder = &MockTokenSerivceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSerivceInterface) EXPECT() *MockTokenSerivceInterfaceMockRecorder {
	return m.recorder
}

// BuildTokenString mocks base method.
func (m *MockTokenSerivceInterface) BuildTokenString(userClaims auth.UserClaims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTokenString", userClaims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildTokenString indicates an expected call of BuildTokenString.
func (mr *MockTokenSerivceInterfaceMockRecorder) BuildTokenString(userClaims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTokenString", reflect.TypeOf((*MockTokenSerivceInterface)(nil).BuildTokenString), userClaims)
}

// GetUserClaims mocks base method.
func (m *MockTokenSerivceInterface) GetUserClaims(tokenString string) (auth.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserClaims", tokenString)
	ret0, _ := ret[0].(auth.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserClaims indicates an expected call of GetUserClaims.
func (mr *MockTokenSerivceInterfaceMockRecorder) GetUserClaims(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserClaims", reflect.TypeOf((*MockTokenSerivceInterface)(nil).GetUserClaims), tokenString)
}
