
### register user
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### login user
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### sync entries
POST {{baseUrl}}/api/entries/sync
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwNzcxODMsIlVzZXJJRCI6ImI2MzJlYjkzLTBjMzEtNGQ2Yy04ZmI5LTI4MmYzZmI3ZTU0ZSJ9.gROyNjjdVgEmHXg543ejgK2XF8QzBrBkeMVQA8heoqw

{
  "items": [
    {
      "originalId": "0bc6c22e-d8b5-4057-9d28-eb5b7a233364",
      "type": "login",
      "data": "MX1mUs+puMP3FNlWITgzf5vS2JmcsVu/AivvxURLiQaPQJIxeVbF5/zGUBNVWuW5kzWhHKAi4E+gtoQ8Y9k=",
      "isDeleted": false,
      "updatedAt": "2020-12-10T15:15:45+00:00",
      "meta": {
        "property1": "string",
        "property2": "string"
      }
    },
    {
      "originalId": "3da6111c-6316-4993-aeff-74a2c3f345f9",
      "type": "card",
      "data": "2DAKVANzdYtKSMvMj11o/wEI8NnCZI3UkPu6z2UZtnOkdKSzdGddkkvu7EKST2OQ0Hcus7nfaosO/agavL8=",
      "isDeleted": false,
      "updatedAt": "2020-12-10T15:15:45+00:00",
      "meta": {
        "property1": "string",
        "property2": "string"
      }
    }
  ]
}